services:
  netbox:
    volumes:
      - ./configuration:/etc/netbox/config:ro
      - ./data/media:/opt/netbox/netbox/media:rw
      - ./data/reports:/opt/netbox/netbox/reports:rw
      - ./data/scripts:/opt/netbox/netbox/scripts:rw

  netbox-worker:
    volumes:
      - ./configuration:/etc/netbox/config:ro
      - ./data/media:/opt/netbox/netbox/media:rw
      - ./data/reports:/opt/netbox/netbox/reports:rw
      - ./data/scripts:/opt/netbox/netbox/scripts:rw

  postgres:
    volumes:
      - netbox-lab-postgres:/var/lib/postgresql

  redis:
    command:
      - sh
      - -c
      - valkey-server --appendonly yes --requirepass $$REDIS_PASSWORD --save ""
    volumes:
      - ./data/redis:/data

  redis-cache:
    command:
      - sh
      - -c
      - valkey-server --requirepass $$REDIS_PASSWORD --save ""
    volumes:
      - ./data/redis-cache:/data

volumes:
  netbox-lab-postgres:
    driver: local
